# Site
repository: liuliu-umich/liuliu-umich.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Liu Liu
title: Data Scientist and Biomedicine Professor
email: 
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: liuliu-umich.github.io
# website_title: Web (Website title override)
# blog_name: Blog
# blog_title: Blog (Blog title override)
# projects_title: My projects
# projects_name: Web (Website title override)


# Base URL (set this if your site is not at the root of the domain)
baseurl: "" # Leave it empty if your site is at the root of the domain
# url: "http://localhost:4000" # The base URL for your local development, or your production URL
url: "http://liuliu-umich.github.io" # Leave it empty if your site is at the root of the domain. Set to "/your-subdirectory" if it is in a subdirectory.

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: 
github_username: liuliu-umich
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: liuliu-umich
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
orcid_username: 0000-0001-8905-1039
googlescholar_username: w77PTjUAAAAJ&hl=en

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/Headshot.jpeg
about_content: | 
  I am a Data Scientist and Assistant Professor at the University of Michigan in Healthcare and Biotechnology, specialized in Machine Learning Modeling for Data-Driven Innovation, Insight Extraction, and Decision Making. My strengths include Problem-Solving, Leadership, and Communication in complex, cross-functional projects.

  &nbsp;

  My expertise includes:
  - Languages: Python, R, SQL, Linux
  - ML & DL: Pandas, Scikit-Learn, PyTorch
  - GenAI: LLM, LangChain, RAG, Hugging Face
  - Cloud & DevOps: AWS, Databricks, Git, Flask
  - Bioinformatics Tools

content:
  - title: Projects
    layout: list
    content:
      - layout: left
        border: weak
        title: Drug Target Detector
        link: https://sproogen.github.io/modern-resume
        link_text: Check My Paper
        additional_links:
          - title: GitHub
            icon: fab fa-github
            url: https://github.com/liuliu-umich/1433predictor
            icon_style: "font-size: 0.8em;"
        description: |
          Implemented a Heart Drug Target Detector to identify drug targets from 1.4 billion candidates, achieving a precision score of 0.91.

          Led a team of 3 data scientists to extract data from 8 million articles, using NLP and LLM techniques for feature generation. Applied feature selection with Boruta and mRMR, trained models (Logistic Regression, Random Forest, XGBoost, SVM, CNN), and deployed the model as a Flask app on AWS.

      - layout: left
        border: weak
        title: AI Paper Analyzer
        link: https://sproogen.github.io/modern-resume
        link_text: Check My Web
        additional_links:
          - title: GitHub
            icon: fab fa-github
            url: https://github.com/liuliu-umich/AI-Paper-Analyzer/tree/main
            icon_style: "font-size: 0.8em;"
        description: |
          Developed an AI-powered end-to-end MVP that automates paper selection, content extraction, and generation, reducing research time by 100 hours per project.
 
          Collaborated with a cross-functional team to implement RAG with Chroma vector databases and GPT-4. Developed a Flask-based backend and API, coordinated with front-end and product manager teams, and deployed the application on Azure.

      - layout: left
        border: weak
        title: Heart Attack Detector
        link: https://sproogen.github.io/modern-resume
        link_text: Project Details
        additional_links:
          - title: GitHub
            icon: fab fa-github
            url: https://github.com/liuliu-umich/Heart-Attack-Detector
            icon_style: "font-size: 0.8em;"
        description: |
          Developed a Heart Attack Detector using health data, achieving a recall score of 0.81.

          To identify high-risk individuals for heart attacks, I integrated data from a local hospital database and web scraping. Derived features using historical survival analysis models and trained multiple classification models, including KNN, XGBoost, and Artificial Neural Networks.

      - layout: left
        border: weak
        title: Genes Insight Engine
        link: 
        link_text: 
        additional_links:
          - title: GitHub
            icon: fab fa-github
            url: https://github.com/liuliu-umich/NGS-pipeline
            icon_style: "font-size: 0.8em;"
        description: |
          To identify gene targets promoting heart regeneration, I developed a bioinformatics data analysis pipeline. Collected and processed RNA-seq data, performed Quality Control, Read Mapping, and Quantification. Applied bioinformatics analysis to extract insights, leading to the discovery of 47 heart repair genes.


  - title: Experience
    layout: list
    content:
      - layout: left
        title: University of Michigan
        sub_title: Assistant Professor
        caption: September 2023 - Present
        link: https://medicine.umich.edu/dept/cardiac-surgery/liu-liu-phd-ms
        description: |
          Leading data science projects and academic research at the intersection of Healthcare and AI.

          Spearheaded the development of the Heart Drug Target Detector and AI Paper-Analysis Engine. Led a team for heart drug studies as Principal Investigator, and securing $210K in competitive funding within one year.

      - layout: left
        title: 
        sub_title: Research Investigator
        caption: December 2018 - August 2023
        description: |
          Developed the Heart Drug Insight Engine and Heart Attack Detector.

          Led the Heart Drug Insight Engine project using NGS data, and deployed the Heart Attack Detector model as Principal Investigator.

      - layout: left
        title: 
        sub_title: Postdoctoral Researcher
        caption: April 2013 - November 2018
        description: |

          &nbsp;

          Developed the Insight Engine for Heart Regeneration Genes, identifying key gene targets for heart repair.

          Developed a bioinformatics data analysis pipeline to identify gene targets promoting heart regeneration. Collected RNA-seq data, performed quality control, read mapping, and quantification for data preprocessing, and applied bioinformatics analysis. Identified 47 genes as heart repair targets.

      - layout: left
        title: Nanjing University
        sub_title: Graduate Research and Teaching Assistant
        caption: March 2008 - March 2013
        description: |
          Applied differential gene expression analysis to identify biomarkers, securing $50K in funding.

          Developed the Pregnancy Disease Insight Engine and identified 7 genes as diagnostic biomarkers.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Nanjing University
        sub_title: Ph.D. in Biology
        caption: September 2008 - March 2013
        description: | 
          Developed bioinformatics data analysis pipelines for heart regeneration research.

      - layout: left
        title: Yangzhou University
        sub_title: M.S. in Genetics
        caption: September 2005 - June 2008
        description: | 
          Focused on genetic research and biotechnology applications.

      - layout: left
        title: Yangzhou University
        sub_title: B.S. in Biotechnology
        caption: September 2001 - June 2005
        description: | 
          Comprehensive education in Biotechnology with a focus on molecular biology.

  - title: A Little More About Me
    layout: text
    content: | 
      I am passionate about using data science and AI to drive innovation in healthcare and biotechnology. My interests include exploring new machine learning techniques, mentoring young professionals, and collaborating on interdisciplinary projects. In my free time, I enjoy reading, hiking, and experimenting with new technologies.

# # Navigation configuration
# navigation:
#   - title: "Home"
#     url: "/"
#   - title: "Blog"
#     url: "/blog/"
#   # Add more navigation links if needed

permalink: /blog/:title/

collections:
  projects:
    output: true

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
]

